### PR TITLE
Add support for multiple sprites

### PR DESCRIPTION
**Pull request by sultanahamer**
Using a single sprite for a huge video is not going to work, either we need to increase interval and loose on number of thumbs per 30 seconds or we create a huge sprite taking all of the memory

Creating multiple sprites will help deal with this issue

Please feel free to make naming / logic improvements

### CODE REVIEW

**Comment by phloxic** [comment]
Thank you for the PR.

I am aware of the problem. However I am not convinced (yet) that chunking the sprite improves the situation, see the discussion on a similar proposal [here](https://github.com/phloxic/videojs-sprite-thumbnails/pull/1).

I don't think this is a memory issue, but a matter of how to handle slower connection speeds because fetching the image(s) competes with fetching the video, and video playback and quality should have higher priority than the display of thumbnails on seek.

In browsers with a Chrome engine or in Edge the plugin offers a good and clean compromise via the `downlink` [option](https://github.com/phloxic/videojs-sprite-thumbnails#configuration): If the connection is too slow no fetch is attempted. For browsers where this is not support I experimented with a 'home-grown' connection speed check (test fetch of a small image, and infer consequences from that), but it felt too much of an unreliable hack.

The scenario to avoid is: You start a seek via the control bar, and the video goes into buffering state and/or tries to emergency downswitch HLS or DASH quality because the loading of the image takes over. To avoid this the plugin, as it stands fetches the sprite image before playback starts. The issue with chunks is that you risk to only postpone the problem or run into it several times.

The current approach might be too puristic, and I am willing to look into this again. However, it won't be quick, not least testing is time consuming. It would definitely help if you could provide a link to page with a working example of your approach.

And of course one should put as much effort into compressing/encoding the sprite(s) as for the video, use the smallest resolution possible etc.

**Comment by sultanahamer** [comment]
@phloxic I understand your concern about loading images might take a toll on video being loaded.

Given this is a generic thumbnails implementation, we need to support major approaches that industry / video service providers come up with, youtube at the moment is following multiple sprites approach.

Some companies might expect their consumers to not have bandwidth issues and might go with multiple sprites approach, in that case, not having a support for it would mean, writing a new thumbnails implementation which supports multiple sprites. Hence the pr.

https://gitlab.com/sultanahamer/newpipeservice here is a application that I use everyday as my youtube replacement

Follow the instructions there
1. download latest jar from readme link
2. run the jar using `java -jar <jar_file_name>`
3. visit the url mentioned in the readme
4. choose use Localhost check box in the ui
5. search for some content
6. click on one of the results
7. play the video

We should be able to see the thumbnails appearing on the video

Also, the implementation in pull request doesn't break the regular single url sprite implementation

**Comment by phloxic** [comment]
@sultanahamer - I had an MWE of your proposal in mind (so I can test whether it deals better with the issue of overlong sprite loading times vs visibly interfering with playback), not a full blown app, which, at least for me, also doesn't display any thumbnails. So it didn't convince me that the approach actually performs better ;-)

As I said, I am aware of the problem, and I will look into again. I will try your branch and do some testing, once I find time.

**Comment by phloxic** [comment]
@sultanahamer - I tried your version.
- Like with your app, it doesn't work. Log says: `VIDEOJS: player: spriteThumbnails: no thumbnails url given`
- Even if it worked, it's unlikely to change the situation because you load [all the sprites in one go in a loop](https://github.com/phloxic/videojs-sprite-thumbnails/pull/52/commits/e17e3c2f044f549e8129481f1eace57751821ee2#diff-c1d2501358bf79c97350f7b8dae70df4ee9ca71237a49cf0a46b96b3e00259b5R190-R192). So one might as well load just one image then; less calls to the server.

imho, for this to make sense the behaviour would have to change from (pre)loading one image at `loadstart`, the sprites have to be loaded _on demand_, when and where the user actually seeks. I will try this approach, and test whether this interferes less or at least not more with playback in the critical scenario of a long video playing over a slow connection.

**Comment by sultanahamer** [comment]
@phloxic it makes sense for images to be loaded on demand

Not sure why you aren't getting the thumbnails served. Its working alright in both chrome and firefox for me.

If you want to test it on a sample video page, You can try to use the response from the api `http://localhost:6060/stream?url=https://www.youtube.com/watch?v=jNfpRZsFmFk` which should have thumbnail urls in response

image

**Comment by phloxic** [comment]
For me[tm] your version still works with a [single splash](https://phloxic.productions/test/videojs/sprite-thumbnails-v8.html), but [not with multiple splashs](https://phloxic.productions/test/videojs/sprite-thumbnails-v8m.html), both in a minmal setup. I also tried various ways to configure the plugin to no avail.

Nevermind, I'll look into an on demand approach at some point.

**Comment by phloxic** [comment]
@sultanahamer - this is now implemented, thank you.

**Comment by sultanahamer** [comment]
> @sultanahamer - this is now implemented, thank you.

Thanks @phloxic

**Pull request closed without merging**
